name: Cron SSH Logs to S3

on:
  # schedule:
  #   # Runs every day at midnight UTC
  #   - cron: "* * * * *"
  workflow_dispatch:
    inputs:
      test_mode:
        description: "This Runs on test mode"
        required: false
        default: "true"

jobs:
  upload-ssh-logs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the Python script
      - name: Run the script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          python upload_logs.py

      # Step 5: Install AWS CLI    
      - name: Configure AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      # Step 6: Run the bash script
      - name: Execute the open ports script
        run: |
          chmod +x ./check_open_ports.sh
          ./check_open_ports.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
